config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    get 'home/index'
    resources :authors, :categories, :publishers
    resources :books
    resources :users do
      collection do
        get :admins
      end
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :author_name, :country, presence: true 
  has_rich_text :biography

  has_many :books 

  paginates_per 5
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :category
  belongs_to :publisher

  has_many_attached :images

  validates :title, :isbn, :launch_year, presence: true 
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true 
  has_rich_text :description
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  validates :title, presence: true
  has_rich_text :description

  has_many :books
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :admins, -> { where(admin: true) }
end

app/controllers/admin/authors_controller.rb
# frozen_string_literal: true

class Admin::AuthorsController < AdminController
  before_action :set_author, only: %i[show edit update destroy]

  def index
    @authors = Author.all.page(params[:page])
  end

  def show; end

  def new
    @author = Author.new
  end

  def edit; end

  def update
    if @author.update(author_params)
      redirect_to admin_author_path(@author.id), notice: 'Autor Atualizado com Sucesso'
    else
      render :edit
    end
  end

  def create
    @author = Author.new(author_params)

    if @author.save!
      redirect_to admin_authors_path
    else
      render :new
    end
  end

  def destroy 
    if @author.destroy!
      redirect_to admin_authors_path
    else
      flash[:error] = @author.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:author_name, :biography, :country)
  end
end

app/controllers/admin/books_controller.rb
# frozen_string_literal: true

class Admin::BooksController < AdminController
  before_action :set_book, only: %i[show destroy edit update]

  def index
    @books = Book.includes(:publisher, :author, :category)
                 .order(created_at: :desc)
                 .page(params[:page])
  end

  def show; end

  def edit
    @publishers = Publisher.all.pluck(:title, :id)
    @authors = Author.all.pluck(:author_name, :id)
    @categories = Category.all.pluck(:title,:id)
  end 

  def new 
    @book = Book.new
    @publishers = Publisher.all.pluck(:title, :id)
    @authors = Author.all.pluck(:author_name, :id)
    @categories = Category.all.pluck(:title,:id)
  end

  def create 
    @book = Book.new(book_params)
    @book.images.attach(params[:book][:images]) 
    
    if @book.save!
      redirect_to admin_books_path
    else
      render :new
    end
  end

  def update
    binding.pry
    @book.images.attach(params[:book][:images])
    if @book.update!(book_params)
      redirect_to admin_book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    if @book.destroy! 
      redirect_to admin_books_path
    else
      render :index
    end
  end

  private 

  def set_book 
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :launch_year, :author_id, :category_id, :publisher_id, :images)
  end
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < AdminController
  before_action :set_category, only: %i[show edit update destroy]
  def index
    @categories = Category.all.page(params[:page])
  end

  def new
    @category = Category.new
  end

  def show; end

  def edit; end

  def create
    @category = Category.new(category_params)

    if @category.save!
      redirect_to admin_categories_path, notice: 'Categoria criada com sucesso'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_category_path(@category.id), notice: 'Categoria atualizada com sucesso'
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy!
      redirect_to admin_categories_path, notice: 'Categoria apagada com sucesso'
    else
      render :index
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def index
    @categories = Category.all.take(5)
    @books = Book.all.take(5)
    @authors = Author.all.take(5)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :verify_password, only: %i[update]

  def index 
    @users = User.order(created_at: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)

    if @user.save! 
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit; end

  def show; end 

  def update 
    if @user.update!(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit 
    end
  end

  def destroy 
    if @user.destroy! 
      redirect_to admin_users_path
    else
      render :index
    end
  end

  def admins
    @users = User.admins.order(created_at: :desc).page(params[:page])
  end


  private 

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation, :admin)
  end

  def verify_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].extract!(:password, :password_confirmation)
    end
  end

end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :authenticate_admin!

  layout 'admin'

  def authenticate_admin!
    authenticate_user!

    redirect_to root_path, notice: 'Você não pode acessar essa área' unless current_user.admin?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  layout :layout_by_resource


  private

  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : 'application'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/authors_helper.rb
module Admin::AuthorsHelper
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/publishers_helper.rb
module Admin::PublishersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def attr_name(object, attribute)
    if defined? object.human_attribute_name(attribute)
      object.human_attribute_name(attribute)
    else
      object.class.human_attribute_name(attribute)
    end
  end

  def obj_name(obj)
    obj.model_name.human(count: obj.count)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/authors/_form.html.erb
<%= form_with model: [:admin, @author], local: true do |f| %>
  <%= render partial: "admin/shared/errors", locals: {resource: @author} %>
  <div class="field">
    <%= f.label :author_name, class: "label" %>
    <div class="control">
      <%= f.text_field :author_name, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :country, class: "label" %>
    <div class="control">
      <%= f.text_field :country, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :biography, class: "label" %>
    <%= f.rich_text_area :biography %>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= f.submit 'Criar', class: 'button is-link' %>
    </div>
    <div class="control">
      <%= link_to 'Voltar', admin_authors_path, class: 'button is-link is-light' %>
    </div>
  </div>
<% end %>

app/views/admin/authors/_table.html.erb
<table class="table is-striped">
  <thead>
    <th><%= attr_name(@authors, :id) %></th>
    <th><%= attr_name(@authors, :author_name) %></th>
    <th><%= attr_name(@authors, :country) %></th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.id %></td>
        <td><%= author.author_name %></td>
        <td><%= author.country %></td>
        <td>
          <%= link_to t('admin.common.show'), admin_author_path(author.id), class: "button is-primary" %>
        </td>
        <td>
          <%= link_to t('admin.common.edit'), edit_admin_author_path(author.id), class: "button is-warning"%>
        </td>
        <td>
          <%= link_to t('admin.common.delete'), admin_author_path(author.id), method: :delete, class: "button is-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @authors %>

app/views/admin/authors/edit.html.erb
<h3 class="title is-3"><%= "Editando #{@author.model_name.human}" %></h3>
<%= render partial: 'form'%>

app/views/admin/authors/index.html.erb
<div class="container">
  <h3 class="title is-3"><%= obj_name(@authors) %></h3>
  <div class="column is-12">
    <%= link_to t('admin.authors.add'), new_admin_author_path, class: "button is-primary" %>
  </div>
  
  <%= render partial: "table" %>
</div>

app/views/admin/authors/new.html.erb
<h3 class="title is-1"><%= t('admin.authors.add') %></h3>
<%= render partial: 'form'%>

app/views/admin/authors/show.html.erb
<div class="container">
  <h3 class="title is-3"><%= @author.author_name %></h2>
  <h5 class="subtitle is-5"><%=  @author.country %></h5>
  <p><%= @author.biography %></p>
</div>

app/views/admin/books/_form.html.erb
<%= form_with model: [:admin, @book], local: true do |f| %>
  <div class="field">
    <%= f.label :title, class: "label" %>
    <div class="control">
      <%= f.text_field :title, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :isbn, class: "label" %>
    <div class="control">
      <%= f.text_field :isbn, class: "input",  size: 13%>
    </div>
  </div>
  <div class="field">
    <%= f.label :launch_year, class: "label" %>
    <div class="control">
      <%= f.number_field :launch_year, class: "input", step: 1, min: 0, max: DateTime.now.year %>
    </div>
  </div>
  <div class="field">
    <%= f.label :author, class: "label" %>
    <div class="select">
      <%= f.select :author_id, @authors, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :category, class: "label" %>
    <div class="select">
      <%= f.select :category_id, @categories, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :publisher, class: "label" %>
    <div class="select">
      <%= f.select :publisher_id, @publishers, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :images, class: "label" %>
    <div class="control">
      <%= f.file_field :images, multiple: true %>
    </div>
  </div>
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit 'Criar', class: 'button is-link' %>
    </div>
    <div class="control">
      <%= link_to 'Voltar', admin_books_path, class: 'button is-link is-light' %>
    </div>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h3 class="title is-3"><%= t('admin.books.edit') %></h3>
<%= render partial: "form" %>

app/views/admin/books/index.html.erb
<div class="container">
  <h3 class="title is-3"><%= obj_name(@books) %></h3>

  <div class="column is-12">
    <%= link_to t('admin.books.add'), new_admin_book_path, class: "button is-primary" %>
  </div>

  <div class="columns is-multiline is-mobile">
    <% @books.each do |book| %>
      <div class="column is-full-mobile is-one-third-desktop">
        <figure class="image is-square">
          <%= image_tag book.images.last %>
        </figure>
        <h4 class="subtitle is-4"><%= book.title %></h4>
        <div class="is-grouped is-centered">
          <%= link_to t('admin.common.show'), admin_book_path(book.id), class: "button is-primary" %>
          <%= link_to t('admin.common.edit'), edit_admin_book_path(book.id), class: "button is-warning" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%=  paginate @books %>

app/views/admin/books/new.html.erb
<h3 class="title is-3"><%= t('admin.books.new') %></h3>
<%= render partial: "form" %>

app/views/admin/categories/_form.html.erb
<%= form_with model: [:admin, @category], local: true do |f| %>
  <%= render partial: "admin/shared/errors", locals: {resource: @category} %>

  <div class="field">
    <%= f.label :title, class: "label" %>
    <div class="control">
      <%= f.text_field :title, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :description, class: "label" %>
    <div class="control">
      <%= f.text_field :description, class: "input" %>
    </div>
  </div>
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit 'Criar', class: 'button is-link' %>
    </div>
    <div class="control">
      <%= link_to 'Voltar', admin_categories_path, class: 'button is-link is-light' %>
    </div>
  </div>
<% end %>

app/views/admin/categories/_table.html.erb
<table class="table is-striped">
  <thead>
    <th><%= attr_name(@categories, :id) %></th>
    <th><%= attr_name(@categories, :title) %></th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.title %></td>
        <td>
          <%= link_to t('admin.common.show'), admin_category_path(category.id), class: "button is-primary" %>
        </td>
        <td>
          <%= link_to t('admin.common.edit'), edit_admin_category_path(category.id), class: "button is-warning" %>
        </td>
        <td>
          <%= link_to t('admin.common.delete'), admin_category_path(category.id), method: :delete, class: "button is-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @categories %>

app/views/admin/categories/edit.html.erb
<h3 class="title is-3">
  <%= t('admin.categories.edit') %>
</h3>

<%= render partial: "form" %>

app/views/admin/categories/index.html.erb
<div class="container">
  <h3 class="title is-3"><%= obj_name(@categories) %></h3>
  <div class="column is-12">
    <%= link_to t('admin.categories.add'), new_admin_category_path, class: "button is-primary" %>
  </div>
  
  <%= render partial: "table" %>
</div>

app/views/admin/categories/new.html.erb
<h3 class="title is-3">
  <%= t('admin.categories.new') %>
</h3>
<%= render partial: "form" %>

app/views/admin/categories/show.html.erb
<h3 class="title is-3">
  <%= t('admin.categories.show', category_name: @category.title) %>
</h3>

<div class="container">
  <h4 class="title is-4"><%= @category.title %></h4>
  <h6 class="subtitle is-6"><%= @category.description %></h6>
</div>

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin, @user], local: true do |f| %>
  <%= render "users/shared/error_messages", resource: @user %>

  <div class="field">
    <%= f.label :full_name, class: "label" %>
    <div class="control">
      <%= f.text_field :full_name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :email, class: "label" %>
    <div class="control">
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :password, class: "label" %>
    <div class="control">
      <%= f.password_field :password, autocomplete: "new-password", class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, class: "label" %>
    <div class="control">
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "input" %>
    </div>
  </div>


  <div class="field">
    <%= f.check_box :admin %>
    <%= f.label :admin, class: "checkbox"%>
  </div>

  <div class="field is-grouped">
    <%= f.submit "Criar", class: "button is-link" %>
    <%= link_to "Voltar", admin_users_path , class: 'button is-link is-light' %> 
  </div>
<% end %>

app/views/admin/users/_table.html.erb
<table class="table is-striped">
  <thead>
    <th><%= attr_name(@users, :id) %></th>
    <th><%= attr_name(@users, :full_name) %></th>
    <th><%= attr_name(@users, :email) %></th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to t('admin.common.show'), admin_user_path(user.id), class: "button is-primary" %>
        </td>
        <td>
          <%= link_to t('admin.common.edit'), edit_admin_user_path(user.id), class: "button is-warning"%>
        </td>
        <% unless current_user == user %>
          <td>
            <%= link_to t('admin.common.delete'), admin_user_path(user.id), method: :delete, class: "button is-danger" %>
          </td>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/admins.html.erb
<div class="container">
  <h3 class="title is-3">Administradores</h3>
  
  <%= render partial: "table" %>
</div>

app/views/admin/users/edit.html.erb
<h3 class="title is-3"><%= t('admin.users.edit') %></h3>
<%= render partial: "form" %>

app/views/admin/users/index.html.erb
<div class="container">
  <h3 class="title is-3"><%= obj_name(@users) %></h3>
  <div class="column is-12">
    <%= link_to t('admin.users.add'), new_admin_user_path, class: "button is-primary" %>
  </div>
  
  <%= render partial: "table" %>
</div>

app/views/admin/users/new.html.erb
<h3 class="title is-3"><%= t('admin.users.new') %></h3>
<%= render partial: "form" %>

app/views/admin/users/show.html.erb
<div class="container">
  <h3 class="title is-3"><%= @user.full_name %></h2>
  <h5 class="subtitle is-5"><%=  @user.email%></h5>
  <% if @user.admin? %>
    <p class="text-light">Administrador</p>
  <% else %>
    <p class="text-light">Usuário Comum</p>
  <% end %>
</div>