config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    get 'home/index'
    resources :authors, :categories, :publishers
    resources :books
    resources :users do
      collection do
        get :admins
      end
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :author_name, :country, presence: true 
  has_rich_text :biography

  has_many :books 

  paginates_per 5
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :category
  belongs_to :publisher

  has_many_attached :images

  validates :title, :isbn, :launch_year, presence: true 
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true 
  has_rich_text :description
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  validates :title, presence: true
  has_rich_text :description

  has_many :books
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :admins, -> { where(admin: true) }
end

app/controllers/admin/authors_controller.rb
# frozen_string_literal: true

class Admin::AuthorsController < AdminController
  before_action :set_author, only: %i[show edit update destroy]

  def index
    @authors = Author.all.page(params[:page])
  end

  def show; end

  def new
    @author = Author.new
  end

  def edit; end

  def update
    if @author.update(author_params)
      redirect_to admin_author_path(@author.id), notice: 'Autor Atualizado com Sucesso'
    else
      render :edit
    end
  end

  def create
    @author = Author.new(author_params)

    if @author.save!
      redirect_to admin_authors_path
    else
      render :new
    end
  end

  def destroy 
    if @author.destroy!
      redirect_to admin_authors_path
    else
      flash[:error] = @author.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:author_name, :biography, :country)
  end
end

app/controllers/admin/books_controller.rb
# frozen_string_literal: true

class Admin::BooksController < AdminController
  before_action :set_book, only: %i[show destroy edit update]

  def index
    @books = Book.includes(:publisher, :author, :category)
                 .order(created_at: :desc)
                 .page(params[:page])
  end

  def show; end

  def edit
    @publishers = Publisher.all.pluck(:title, :id)
    @authors = Author.all.pluck(:author_name, :id)
    @categories = Category.all.pluck(:title,:id)
  end 

  def new 
    @book = Book.new
    @publishers = Publisher.all.pluck(:title, :id)
    @authors = Author.all.pluck(:author_name, :id)
    @categories = Category.all.pluck(:title,:id)
  end

  def create 
    @book = Book.new(book_params)
    @book.images.attach(params[:book][:images]) 
    
    if @book.save!
      redirect_to admin_books_path
    else
      render :new
    end
  end

  def update
    binding.pry
    @book.images.attach(params[:book][:images])
    if @book.update!(book_params)
      redirect_to admin_book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    if @book.destroy! 
      redirect_to admin_books_path
    else
      render :index
    end
  end

  private 

  def set_book 
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :launch_year, :author_id, :category_id, :publisher_id, :images)
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def index
    @categories = Category.all.take(5)
    @books = Book.all.take(5)
    @authors = Author.all.take(5)
  end
end

app/controllers/admin/publishers_controller.rb
# frozen_string_literal: true

class Admin::PublishersController < AdminController
  before_action :set_publisher, only: %i[show destroy edit update]

  def index
    @publishers = Publisher.all.page(params[:page])
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save!
      redirect_to admin_publishers_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @publisher.update(publisher_params)
      redirect_to admin_publisher_path(@publisher.id)
    else
      render :edit
    end
  end

  def show; end

  def destroy
    if @publisher.destroy!
      redirect_to admin_publishers_path
    else
      render :index
    end
  end

  private

  def set_publisher
    @publisher = Publisher.find(params[:id])
  end

  def publisher_params
    params.require(:publisher).permit(:title, :country, :description)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :verify_password, only: %i[update]

  def index 
    @users = User.order(created_at: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)

    if @user.save! 
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit; end

  def show; end 

  def update 
    if @user.update!(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit 
    end
  end

  def destroy 
    if @user.destroy! 
      redirect_to admin_users_path
    else
      render :index
    end
  end

  def admins
    @users = User.admins.order(created_at: :desc).page(params[:page])
  end


  private 

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation, :admin)
  end

  def verify_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].extract!(:password, :password_confirmation)
    end
  end

end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :authenticate_admin!

  layout 'admin'

  def authenticate_admin!
    authenticate_user!

    redirect_to root_path, notice: 'Você não pode acessar essa área' unless current_user.admin?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  layout :layout_by_resource


  private

  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : 'application'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/authors_helper.rb
module Admin::AuthorsHelper
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/publishers_helper.rb
module Admin::PublishersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def attr_name(object, attribute)
    if defined? object.human_attribute_name(attribute)
      object.human_attribute_name(attribute)
    else
      object.class.human_attribute_name(attribute)
    end
  end

  def obj_name(obj)
    obj.model_name.human(count: obj.count)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/publishers/_form.html.erb
<%= form_with model: [:admin, @publisher], local: true do |f| %>
  <%= render partial: "admin/shared/errors", locals: {resource: @publisher} %>
  
  <div class="field">
    <%= f.label :title, class: "label" %>
    <div class="control">
      <%= f.text_field :title, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :country, class: "label" %>
    <div class="control">
      <%= f.text_field :country, class: "input" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :description, class: "label" %>
    <div class="control">
      <%= f.rich_text_area :description %>
    </div>
  </div>
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit 'Criar', class: 'button is-link' %>
    </div>
    <div class="control">
      <%= link_to 'Voltar', admin_publishers_path, class: 'button is-link is-light' %>
    </div>
  </div>
<% end %>

app/views/admin/publishers/_table.html.erb
<table class="table is-striped">
  <thead>
    <th><%= attr_name(@publishers, :id) %></th>
    <th><%= attr_name(@publishers, :title) %></th>
    <th><%= attr_name(@publishers, :country) %></th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.id %></td>
        <td><%= publisher.title %></td>
        <td><%= publisher.country %></td>
        <td>
          <%= link_to t('admin.common.show'), admin_publisher_path(publisher.id), class: "button is-primary" %>
        </td>
        <td>
          <%= link_to t('admin.common.edit'), edit_admin_publisher_path(publisher.id), class: "button is-warning"%>
        </td>
        <td>
          <%= link_to t('admin.common.delete'), admin_publisher_path(publisher.id), method: :delete, class: "button is-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @publishers %>

app/views/admin/publishers/edit.html.erb
<h3 class="title is-3"><%= "Editando #{@publisher.model_name.human}" %></h3>
<%= render partial: 'form'%>

app/views/admin/publishers/index.html.erb
<div class="container">
  <h3 class="title is-3"><%= obj_name(@publishers) %></h3>
  <div class="column is-12">
    <%= link_to t('admin.publishers.add'), new_admin_publisher_path, class: "button is-primary" %>
  </div>
  
  <%= render partial: "table" %>
</div>

app/views/admin/publishers/new.html.erb
<h3 class="title is-3">
  <%= t('admin.publishers.new') %>
</h3>

<%= render partial: "form" %>