config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    get 'home/index'
    resources :authors, :categories, :publishers
    resources :books
    resources :users do
      collection do
        get :admins
      end
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :author_name, :country, presence: true 
  has_rich_text :biography

  has_many :books 

  paginates_per 5
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :category
  belongs_to :publisher

  has_many_attached :images

  validates :title, :isbn, :launch_year, presence: true 
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true 
  has_rich_text :description
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  validates :title, presence: true
  has_rich_text :description

  has_many :books
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :admins, -> { where(admin: true) }
end

app/controllers/admin/books_controller.rb
# frozen_string_literal: true

class Admin::BooksController < AdminController
  before_action :set_book, only: %i[show destroy edit update]

  def index
    @books = Book.includes(:publisher, :author, :category)
                 .order(created_at: :desc)
                 .page(params[:page])
  end

  def show; end

  def edit
    @publishers = Publisher.all.pluck(:title, :id)
    @authors = Author.all.pluck(:author_name, :id)
    @categories = Category.all.pluck(:title,:id)
  end 

  def new 
    @book = Book.new
    @publishers = Publisher.all.pluck(:title, :id)
    @authors = Author.all.pluck(:author_name, :id)
    @categories = Category.all.pluck(:title,:id)
  end

  def create 
    @book = Book.new(book_params)
    @book.images.attach(params[:book][:images]) 
    
    if @book.save!
      redirect_to admin_books_path
    else
      render :new
    end
  end

  def update
    binding.pry
    @book.images.attach(params[:book][:images])
    if @book.update!(book_params)
      redirect_to admin_book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    if @book.destroy! 
      redirect_to admin_books_path
    else
      render :index
    end
  end

  private 

  def set_book 
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :launch_year, :author_id, :category_id, :publisher_id, :images)
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def index
    @categories = Category.all.take(5)
    @books = Book.all.take(5)
    @authors = Author.all.take(5)
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :authenticate_admin!

  layout 'admin'

  def authenticate_admin!
    authenticate_user!

    redirect_to root_path, notice: 'Você não pode acessar essa área' unless current_user.admin?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  layout :layout_by_resource


  private

  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : 'application'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/authors_helper.rb
module Admin::AuthorsHelper
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/publishers_helper.rb
module Admin::PublishersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def attr_name(object, attribute)
    if defined? object.human_attribute_name(attribute)
      object.human_attribute_name(attribute)
    else
      object.class.human_attribute_name(attribute)
    end
  end

  def obj_name(obj)
    obj.model_name.human(count: obj.count)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %></h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin - Biblioteca Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin' %>
  </head>

  <body>
    <nav class="navbar is-dark">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "MyBooks", admin_home_index_path, class: "navbar-item brand-text" %>

          <div class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div id="navMenu" class="navbar-menu">
          <div class="navbar-start">
            <%= link_to "Autores", admin_authors_path, class: "navbar-item" %>
          </div>
        </div>
        <div class="navbar-end">
          <% if user_signed_in? %>
            <div class="navbar-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="columns">
        <div class="column is-3">
          <aside class="menu is-hidden-mobile">
            <p class="menu-label">Geral</p>
            <ul class="menu-list">
              <li>
                <%= link_to "Autores", admin_authors_path %>
              </li>
              <li>
                <%= link_to "Categorias", admin_categories_path %>
              </li>
              <li>
                <%= link_to "Editoras", admin_publishers_path %>
              </li>

              <li>
                <%= link_to "Livros", admin_books_path %>
              </li>
            </ul>
            <p class="menu-label">Aplicação</p>
            <ul class="menu-list">
              <li>
                <%= link_to "Usuários", admin_users_path%>
              </li>
              <li>
                <%= link_to "Administradores", admins_admin_users_path %>
              </li>
            </ul>
          </aside>
        </div>
        <div class="column is-9">
          <%= yield %>
        </div>
      </div>

    </div>

  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BibliotecaRails</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to "MyBooks", root_path, class: "navbar-item" %>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
        data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item">
          Home
        </a>

        <a class="navbar-item">
          Documentation
        </a>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>

          <div class="navbar-dropdown">
            <a class="navbar-item">
              About
            </a>
            <a class="navbar-item">
              Jobs
            </a>
            <a class="navbar-item">
              Contact
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
              Report an issue
            </a>
          </div>
        </div>
      </div>

      <div class="navbar-end">
        <% if current_user.present? %>
          <% if current_user.admin? %>
            <%= link_to "Área Administrativa", admin_home_index_path, class: "navbar-item" %>
          <% end %>
          <div class="navbar-item">
            <div class="buttons">
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "button is-danger" %>
            </div>
          </div>
        <% end %>

        <% unless user_signed_in? %>
          <div class="navbar-item">
            <div class="buttons">
              <%= link_to "Cadastrar-se", new_user_registration_path, class: "button is-primary" %>
              <%= link_to "Login", new_user_session_path, class: "button is-light" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>

</html>

app/views/layouts/user_devise.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'user_devise' %>
  </head>
  <body>
    <section class="hero is-fullheight">
      <div class="hero-body has-text-centered">
        <%= yield %>
      </div>
    </section>
  </body>
</html>